name: Capture Merge Details from Main to Dev

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  capture-merge-details:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev' && github.event.pull_request.head.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Capture merge details
        run: |
          mkdir -p loghistory
          UNIQUE_ID=$(date +%Y%m%d%H%M%S)-${{ github.sha }}
          echo "Merge Timestamp: $(date)" > loghistory/merge_${UNIQUE_ID}.txt
          echo "Merged By: ${{ github.actor }}" >> loghistory/merge_${UNIQUE_ID}.txt
          echo "PR Title: ${{ github.event.pull_request.title }}" >> loghistory/merge_${UNIQUE_ID}.txt
          echo "PR Number: ${{ github.event.pull_request.number }}" >> loghistory/merge_${UNIQUE_ID}.txt
          echo "Commit SHA: ${{ github.event.pull_request.merge_commit_sha }}" >> loghistory/merge_${UNIQUE_ID}.txt

      - name: Commit merge log
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add loghistory/
          git commit -m "Log merge from main to dev: ${UNIQUE_ID}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
