name: Capture and Commit PR Details (Windows)

on:
  pull_request:
    types: [opened, closed]

jobs:
  capture-pr-info:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        shell: pwsh

      - name: Capture PR details and store in CSV
        shell: pwsh
        run: |
          $file = "pr_details.csv"
          if (-not (Test-Path $file)) {
              "timestamp,pr_number,title,author,created_at,state,merged,merged_at,base_branch,head_branch,repository" | Out-File -FilePath $file -Encoding utf8
          }

          $timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
          $prNumber  = "${{ github.event.pull_request.number }}"
          $title     = "${{ github.event.pull_request.title }}".Replace('"', '""')
          $author    = "${{ github.event.pull_request.user.login }}"
          $createdAt = "${{ github.event.pull_request.created_at }}"
          $state     = "${{ github.event.pull_request.state }}"
          $merged    = "${{ github.event.pull_request.merged }}"
          $mergedAt  = "${{ github.event.pull_request.merged_at }}"
          $base      = "${{ github.event.pull_request.base.ref }}"
          $head      = "${{ github.event.pull_request.head.ref }}"
          $repo      = "${{ github.repository }}"

          $line = "$timestamp,$prNumber,""$title"",$author,$createdAt,$state,$merged,$mergedAt,$base,$head,$repo"
          Add-Content -Path $file -Value $line

          Write-Host "✅ PR details appended to $file"
          Get-Content $file | Select-Object -Last 5

      - name: Commit and push CSV log
        shell: pwsh
        run: |
          git add pr_details.csv
          git commit -m "Update PR log for #${{ github.event.pull_request.number }}" -a || Write-Host "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
