name: Capture PR Metadata

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  capture-pr-details:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check system Python
        run: |
          python --version
          Get-Command python

      - name: Install requests
        run: |
          pip install requests

      - name: Capture PR metadata
        shell: powershell
        run: python scripts/capture_pr_metadata.py
        env:
          PYTHONIOENCODING: utf-8
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
