name: Capture and Commit PR Details

on:
  pull_request:
    types: [opened, closed]

jobs:
  capture-pr-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Capture PR details and store in CSV
        run: |
          FILE="pr_details.csv"

          # Create file with header if it doesn’t exist
          if [ ! -f "$FILE" ]; then
            echo "timestamp,pr_number,title,author,created_at,state,merged,merged_at,base_branch,head_branch,repository" > "$FILE"
          fi

          # Append PR details
          echo "$(date '+%Y-%m-%d %H:%M:%S'),${{ github.event.pull_request.number }},\"${{ github.event.pull_request.title }}\",${{ github.event.pull_request.user.login }},${{ github.event.pull_request.created_at }},${{ github.event.pull_request.state }},${{ github.event.pull_request.merged }},${{ github.event.pull_request.merged_at }},${{ github.event.pull_request.base.ref }},${{ github.event.pull_request.head.ref }},${{ github.repository }}" >> "$FILE"

          echo "✅ PR details appended to $FILE"
          cat "$FILE"

      - name: Commit and push CSV log
        run: |
          git add pr_details.csv
          git commit -m "Update PR log for #${{ github.event.pull_request.number }}" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
